name: format docs
on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: densuke/sphinx
      volumes:
        - docs:/work
    steps:
      - name: build
        run: |
          make clean
          make html


