name: format docs
on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: build
        run: |
          cp -r docs /tmp/
          docker run --rm -v /tmp/docs:/work densuke/sphinx make clean html
      - name: gh-pages
        run: |
          git checkout -b gh-pages
          cp -r /tmp/docs/build/* .
          [ ! -f /.nojekyll ] && touch /.nojekyll
          git add .
          git commit -m "auto commit"
          git push -u origin gh-pages


