name: format docs
on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: build
        run: |
          cp -r docs /tmp/
          docker run --rm -v /tmp/docs:/work densuke/sphinx make clean html
          cp index-redirect.html /tmp/
      - name: gh-pages
        run: |
          git fetch
          git checkout gh-pages
          cp -r /tmp/docs/build/* .
          [ ! -f .nojekyll ] && touch .nojekyll
          cp -u /tmp/index-redirect.html ./index.html
          git add .
          git config --global user.email "densuke@st.kobedenshi.ac.jp"
          git config --global user.name "SATO Daisuke(Auto commit)"
          git commit -m "auto commit"
          git push -u origin gh-pages


